### ISSUE TITLE
MultiSelector Longlist will be broken

### ISSUE THREAD

**Issue by yhsiang** [appier/react-component-template#1]
![screen shot 2016-10-24 at 3 37 51 pm](https://cloud.githubusercontent.com/assets/93509/19637145/1891ea84-9a00-11e6-9283-644ce9f9ee61.png)

When we select too many items, its display will be broken.

**Comment by mofas** [comment]
Fixed by e2de9cbe2cb570e0dcad6c88f29711c51deb6e1e
